name: Akamai SIEM Connector Pipeline

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - "*.md"
      - "LICENSE"

jobs:
  build:
    name: Jobs
    runs-on: ubuntu-latest

    steps:
    - name: 1. Download the project files
      uses: actions/checkout@v3

    - name: 2. Install Terraform client
      run: npm install terraform@latest -g

    - name: 3. Deploy
      env:
        LINODE_TOKEN: ${{ secrets.LINODE_TOKEN }}
        LINODE_OBJECT_STORAGE_ACCESS_KEY: ${{ secrets.LINODE_OBJECT_STORAGE_ACCESS_KEY }}
        LINODE_OBJECT_STORAGE_ACCESS_SECRET: ${{ secrets.LINODE_OBJECT_STORAGE_ACCESS_SECRET }}
        SSH_PUBLIC_KEY: ${{ secrets.SSH_PUBLIC_KEY }}
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        RUNNING_IN_A_PIPELINE: true
      run: ./deploy.sh